# Generated by Django 5.1.7 on 2025-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_profile_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
