# Generated by Django 5.1.7 on 2025-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_profile_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
