# Generated by Django 5.1.7 on 2025-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profile_hit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hit_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
